server:
  port: 80
  
  

eureka: 
  client: 
    register-with-eureka: false
    service-url: 
      defaultZone: http://demo:demo@eureka-7001.com:7001/eureka,http://demo:demo@eureka-7002.com:7002/eureka,http://demo:demo@eureka-7003.com:7003/eureka  