server:
  port: 80

logging:
  level:
    ccom.wzy.service: DEBUG
feign:
  hystrix: 
    enabled: true 
  compression:
    request:
      mime-types:       # 可以被压缩的类型
      - text/xml
      - application/xml
      - application/json
      min-request-size: 2048 # 超过2048的字节进行压缩

eureka: 
  client: 
    register-with-eureka: false
    service-url: 
      defaultZone: http://demo:demo@eureka-7001.com:7001/eureka,http://demo:demo@eureka-7002.com:7002/eureka,http://demo:demo@eureka-7003.com:7003/eureka