server:
  port: 8101
eureka: 
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://demo:demo@eureka-7001.com:7001/eureka,http://demo:demo@eureka-7002.com:7002/eureka,http://demo:demo@eureka-7003.com:7003/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: dept-8001.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址
info: 
  app.name: wzy-springclouddemo
  company.name: www.wzy.com
  build.artifactId: $project.artifactId$
  build.version: $project.verson$
spring: 
  application:
    name: springclouddemo-provider-company
